### PR TITLE
fixed emitters and tests and unskip tests

### PR DESCRIPTION
**Pull request by itaibh**

### CODE REVIEW

**Review by kyrylodolynskyi — COMMENTED** [review]
What is `SearchContext`?

**Comment by itaibh** [comment]
`SearchContext` is the Java interface name (in C# it's called `ISearchContext`) for all the `FindElement` methods.

**Comment by kyrylodolynskyi** [comment]
@itaibh okay, this is what I assumed. I am not sure we should use some interface here when we know exactly what the class of the object we will get. In JS it is called `ShadowRoot`, do you have anything like this in dotnet?

**Comment by itaibh** [comment]
@kyrylodolynskyi it's generally better to use interfaces, and I think it's especially true for generated code when you don't know the exact type and you want to be as generic as possible.

**Comment by itaibh** [comment]
@kyrylodolynskyi we do have `ShadowCode` in dotnet but I'm not sure that's how it's called in other places and I wanted not to support too many types, so interface was good option.
We already use `WebElement` which is an interface in Java (called `IWebElement` in C#) so I followed the same pattern.

**Comment by kyrylodolynskyi** [comment]
@itaibh I beliave, we know exactly what we will get here unless something will change in the framework itself (then I would like to know about it by seeing that something is failing). We should not forget that multiple languages will use this code, and we should try to use common abstractions, there is no `SerachContext` in JS (for instance), but there is a `ShadowRoot` class.
And another argument, since I know exactly what will be returned from this script, I can add something else to the test, except calling `.findElement`.

**Comment by itaibh** [comment]
@kyrylodolynskyi that's the problem when trying to generate code for both strongly and weakly typed languages.
What do you suggest then? In C# and in Java there's `ISearchContext` and `SearchContext` respectively, which are interfaces. In JavaScript the `ShadowRoot` is the place when `findElement` is implemented. I'm not sure about other languages.
Perhaps I'll change the type to `ShadowRoot` and use it as is? I couldn't find anything else implementing this metrhod.

**Review by kyrylodolynskyi — APPROVED** [review]

**Pull request merged**
