### PR TITLE
Add bigPages tests to generic list

### PR DESCRIPTION
**Pull request by YuriiChere**
This PR instead of the same PR https://github.com/applitools/sdk.coverage.tests/pull/37

### CODE REVIEW

**Comment by kyryloonufriiev** [comment]
Sorry for emphasizing naming again. 
What the difference between "large" and "long"?

**Comment by amitzur** [comment]
I think **large** should be renamed to **wide**

**Comment by itaibh** [comment]
@amitzur but it's not just wide. wide pages are fine as long as they are not long as well. Large means they are below the maximum allowed length, but over the maximum allowed area (or number of pixels, or width * height or whatever you want to call it).

**Comment by amitzur** [comment]
@itaibh nice, I like the explanation :)

**Comment by amitzur** [comment]
I propose instead of 2 tests, having 1 test with all variants:
```
test('check limit to maximum image size', {
  variants: {
    'for long page with css stitching': {page: 'Long', config: {stitchMode: 'CSS'}},
    'for long page with scroll stitching': {page: 'Long', config: {stitchMode: 'Scroll'}},
    'for long page with vg': {page: 'Long', vg: true},
    'for large page with css stitching': {page: 'Large', config: {stitchMode: 'CSS'}},
    'for large page with scroll stitching': {page: 'Large', config: {stitchMode: 'Scroll'}},
    'for Large page with vg': {page: 'Large', vg: true},
  },
  test({eyes}) {
    eyes.open({appName: 'Eyes Selenium SDK - Test Big Pages', viewportSize})
    eyes.check({region: '#overflowing-div', isFully: true})
    eyes.close()
  },
})
```
The `baselineName` configuration isn't needed since this is a new test, so it will create the baseline with its own name automatically.

**Comment by amitzur** [comment]
Where do we stand with this PR?

**Pull request closed without merging**
